### PR TITLE
Update monerod to v0.18.3.3

### PR DESCRIPTION
**Pull request by napoly**
I am reverting back from `bullseye` to `stretch` because the folder permissions don't work well for the wallet.

@sethforprivacy Could you please take a look?

### CODE REVIEW

**Comment by sethforprivacy** [comment]
What specific issues are you having? Mine has been running flawlessly for quite a while but I know some have had permissions issues in the past.

**Comment by napoly** [comment]
Thanks for the quick reply! I took on the path to resolve some problems/bounties with this project (still completely new here). The first thing that needs to be fixed is the local development setup. It all boils down to running a dockerized monerod with a wallet. Was looking [here](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer.Tests/docker-compose.altcoins.yml#L312-L332) and [here](https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/monero.yml)..but I wasn't able to run it.. as the wallet was/is trowing an error:

```
E Wallet initialization failed: the password file specified could not be read
```
I thought this used to work, so I started to revert the Docker images. After some tweaks I was able to run it with stretch image and the difference was with the ownership of the wallet sub-folders once I attached myself to that docker instance. But looking at it again the stretch is already [archived](https://www.debian.org/distrib/archive).. so bullseye has to be OK.. and the problem needs to be fixed within the docker compose.. changing `--wallet-file=/wallet/wallet --password-file=/wallet/password` to `--wallet-dir=/wallet` works..

I will create another PRs to make it work and leave this only as a version bump

**Comment by napoly** [comment]
@sethforprivacy @Kukks can you pls re-check as from my side this is done.. I believe it has to be merged up in order to get to DockerHub..

**Comment by napoly** [comment]
resolves https://github.com/btcpayserver/dockerfile-deps/issues/69

**Comment by sethforprivacy** [comment]
@napoly I'm seeing multiple reports of issues in Mattermost and X of wallet problems after this was merged. Did you test full wallet functionality? Existing wallets are not syncing properly now. i.e.:

https://x.com/EatAupa/status/1803047959724212552
https://chat.btcpayserver.org/btcpayserver/pl/ririyttwiid58b81da8edwg3rw

**Pull request merged**
