### PR TITLE
Further optimize Docker image layers per DL3059

### PR DESCRIPTION
**Pull request by sethsimmons**
This commit removes unnecessary layers from the resulting Docker image per DL3059:

https://github.com/hadolint/hadolint/wiki/DL3059

The resulting Docker image is otherwise unchanged.

### CODE REVIEW

**Review by Kukks — CHANGES_REQUESTED** [review]
I changed the tagging system so that every revision is now stored for auditability and a simpler tagging bash script. Can you create `Monero/0.17.2.0-1` folder and do the changes in there instead?

**Comment by sethsimmons** [comment]
Ah, yes, I can make that change.

Will push shortly.

**Review by sethsimmons — COMMENTED** [review]
Reverted changes to v0.17.2.0 folder and re-pushed to the new v0.17.2.0-1 folder.

**Review by Kukks — APPROVED** [review]
lgtm

**Pull request merged**
