### PR TITLE
Docker Image: Dash Core v0.14.0.1

### PR DESCRIPTION
**Pull request by snogcel**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
You need to create a new folder.

**Comment by snogcel** [comment]
sure no problem @NicolasDorier, I'm a little confused though -- can you please provide some more detail on this new folder?

**Comment by NicolasDorier** [comment]
Look the structure of all other images. Follow the same structure.

**Comment by snogcel** [comment]
I think we should be all set, please let me know if any other changes are needed. Thanks!

**Comment by snogcel** [comment]
Hello @NicolasDorier and @Kukks I believe this commit reverts the previous changes to v0.14.0: https://github.com/btcpayserver/dockerfile-deps/pull/8/commits/40120189a38b128cd3402dd63d53de07269fd0df. Would it better if I just close this Pull Request and create a new one?

**Comment by NicolasDorier** [comment]
Nop, that's fine. Making new image

**Comment by NicolasDorier** [comment]
done

**Pull request merged**
