### PR TITLE
Version bump to 27.1 for bitcoind

### PR DESCRIPTION
**Pull request by rsafier**
Offer latest 27.1 version

### CODE REVIEW

**Comment by warioishere** [comment]
@NicolasDorier any chance to get this merged into the master branch?

**Review by Kukks — APPROVED** [review]

**Comment by warioishere** [comment]
@Kukks (sorry to mention you again) :D how do I choose bitcoin core 27.1? just doing the testing on elementsd and just wanted to do this testing afterwards? Doesnt bitcoin 27.1 also needs to be placed in 

https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/bitcoin.yml

**Comment by Kukks** [comment]
> @Kukks (sorry to mention you again) :D how do I choose bitcoin core 27.1? just doing the testing on elementsd and just wanted to do this testing afterwards? Doesnt bitcoin 27.1 also needs to be placed in 
> 
> https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/bitcoin.yml

You can't test without modifying the docker repo correct. You can check out the branch of the pull request and run it, but I'm not pushing bitcoin core version without our own testing since it's way more critical than the liquid node

**Comment by warioishere** [comment]
> > @Kukks (sorry to mention you again) :D how do I choose bitcoin core 27.1? just doing the testing on elementsd and just wanted to do this testing afterwards? Doesnt bitcoin 27.1 also needs to be placed in
> > https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/bitcoin.yml
> 
> You can't test without modifying the docker repo correct. You can check out the branch of the pull request and run it, but I'm not pushing bitcoin core version without our own testing since it's way more critical than the liquid node

If you have a minute (not now, not on an hour, but whenever you have time), to explain me how to test this PR, as I said, I'll do and maybe I can help you out with that so you dont need to do that. I have a big btcpay server and a big node running a lot of stuff running, so if it fails on my node, it propably fails on other nodes too haha.

but I am confused how to checkout on this branch on my server. 
I only see those with `git branch`

```
root@btcpay:~/btcpayserver-docker# git branch
  feat/lnd-v0.17.4-beta-rc1
  feat/lnd-v0.18.0-beta
* master
```

sorry I am a total git noob

**Pull request merged**
