### PR TITLE
Bump Dogecoin 1.14.2

### PR DESCRIPTION
**Pull request by astupidmoose**
I've added Dogecoin to the docker-deps repo. Before, it was on an obscure fork of @rockstardev 

This should hopefully make it easier to update in the future. 
I've been able to successfully build locally, however, I'm not 100% confident in it. 

I've noticed some files I've uploaded previously needed chmod on the entrypoint. Not sure how to fix it on my end for commits.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
for future reference ` git update-index --chmod=+x .\Dogecoin\1.14.2\docker-entrypoint.sh `

**Comment by NicolasDorier** [comment]
`btcpayserver/dogecoin:1.14.2` has been created.

Please test it on your instance, then update the ref in btcpayserver-docker.

**Comment by rockstardev** [comment]
> Before, it was on an obscure fork of @rockstardev

That's my thank you for building image 2 years ago.

**Comment by astupidmoose** [comment]
I love you @rockstardev you made many shibes happy for so long!

In @rockstardev we trust!

**Pull request merged**
